# Generated by Django 3.2.20 on 2023-07-24 22:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('S', 'sale'), ('R', 'rent')], max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('bedrooms_num', models.PositiveIntegerField()),
                ('bathroom_num', models.PositiveIntegerField()),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('parking', models.CharField(choices=[('Private', 'Private'), ('Permit', 'Permit')], max_length=15)),
                ('garden', models.CharField(choices=[('Share', 'Share'), ('Private', 'Private')], max_length=15)),
            ],
        ),
    ]
