# Generated by Django 3.2.20 on 2023-07-28 13:23

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_property_property_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='phone number', max_length=31)),
                ('message', models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='furniture',
            field=models.CharField(choices=[('Furnished', 'Furnished'), ('Unfurnished', 'Unfurnished')], max_length=15, null=True),
        ),
    ]
