# Generated by Django 3.2.20 on 2023-07-28 13:35

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20230728_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='furniture',
            field=models.CharField(choices=[('Furnished', 'Furnished'), ('Unfurnished', 'Unfurnished')], max_length=15),
        ),
        migrations.AlterField(
            model_name='viewing',
            name='phone',
            field=phone_field.models.PhoneField(help_text='phone number', max_length=15),
        ),
    ]
