# Generated by Django 3.2.20 on 2023-07-28 13:36

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20230728_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewing',
            name='phone',
            field=phone_field.models.PhoneField(help_text='phone number', max_length=15, null=True),
        ),
    ]
